FROM zkp-verisbom-audit:ubuntu
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends build-essential cmake libmsgsl-dev libflatbuffers-dev flatbuffers-compiler libpoco-dev libssl-dev libgtest-dev
